name: Lint | Test | Build
on:
  push:
    branches:
      - main
      - develop
      - staging
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
      - develop
      - staging
    paths-ignore:
      - '*.md'

jobs:
  eslint:
    name: Eslint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Eslint
        run: yarn lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Prettier
        run: yarn prettier . --check

  test:
    name: Unit & Integration tests
    needs: [eslint, prettier]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run jest with CI option
        run: yarn test:ci

  accpetance:
    name: Smoke & Acceptance tests
    runs-on: ubuntu-latest
    needs: [eslint, prettier]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Smoke & Acceptance tests
        run: |
          yarn build-storybook --quiet
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && yarn test-storybook"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test, accpetance]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build NextJS App
        run: yarn build
