name: Lint | Test | Build
on:
  push:
    branches:
      - main
      - develop
      - staging
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
      - develop
      - staging
    paths-ignore:
      - '*.md'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '18'
          check-latest: true
      - name: Install Npm Dependencies
        run: yarn install
      - name: Eslint
        run: yarn lint
      - name: Prettier
        run: yarn prettier

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '18'
          check-latest: true
      - name: Install Npm Dependencies
        run: yarn install
      - name: Run jest with CI option
        run: yarn test:ci

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '18'
          check-latest: true
      - name: Install Npm Dependencies
        run: yarn install
      - name: Eslint
        run: yarn build
